{"content": {"suites": {"0": {"status": {"total_pass": 3, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_create_role", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_create_role_negative[]", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_create_role_negative[None]", "rerun": "0"}}, "suite_name": "test/api_tests/djnago_app/django_roles/test_create_role.py"}, "1": {"suite_name": "test/api_tests/djnago_app/django_roles/test_put_patch_roles.py", "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_put_role", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_patch_role_negative", "rerun": "0"}, "2": {"status": "xFAIL", "message": "       AssertionError: Incorrect status code for http://localhost:8000/api/roles/15/\n       expected 400\n       actual 200\n", "test_name": "test_patch_role_negative_with_none", "rerun": "0"}}, "status": {"total_pass": 2, "total_skip": 0, "total_xpass": 0, "total_xfail": 1, "total_rerun": 0, "total_fail": 0, "total_error": 0}}, "2": {"suite_name": "test/api_tests/djnago_app/test_django_user/create_users/test_post_users.py", "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_create_users", "rerun": "0"}}, "status": {"total_pass": 1, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 0}}, "3": {"suite_name": "test/api_tests/djnago_app/test_django_user/create_users/test_post_users_negative.py", "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_create_users_wrong_username[None]", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_create_users_wrong_username[empty]", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_create_users_wrong_username[1 char(3 min)]", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_create_users_wrong_username[2 chars(3 min)]", "rerun": "0"}, "4": {"status": "PASS", "message": "", "test_name": "test_create_users_wrong_username[list]", "rerun": "0"}, "5": {"status": "PASS", "message": "", "test_name": "test_create_users_wrong_data_for_properties[username-None]", "rerun": "0"}, "6": {"status": "PASS", "message": "", "test_name": "test_create_users_wrong_data_for_properties[username-empty]", "rerun": "0"}, "7": {"status": "PASS", "message": "", "test_name": "test_create_users_wrong_data_for_properties[password-None]", "rerun": "0"}, "8": {"status": "PASS", "message": "", "test_name": "test_create_users_wrong_data_for_properties[password-empty]", "rerun": "0"}, "9": {"status": "PASS", "message": "", "test_name": "test_create_users_wrong_data_for_properties[email-None]", "rerun": "0"}, "10": {"status": "PASS", "message": "", "test_name": "test_create_users_wrong_data_for_properties[email-empty]", "rerun": "0"}, "11": {"status": "PASS", "message": "", "test_name": "test_create_users_wrong_password[3 char(6 min)]", "rerun": "0"}, "12": {"status": "PASS", "message": "", "test_name": "test_create_users_wrong_password[5 chars(6 min)]", "rerun": "0"}, "13": {"status": "PASS", "message": "", "test_name": "test_create_users_wrong_password[only small]", "rerun": "0"}, "14": {"status": "PASS", "message": "", "test_name": "test_create_users_wrong_password[only capital]", "rerun": "0"}, "15": {"status": "PASS", "message": "", "test_name": "test_create_users_wrong_password[only numbers]", "rerun": "0"}, "16": {"status": "PASS", "message": "", "test_name": "test_create_users_wrong_password[list]", "rerun": "0"}}, "status": {"total_pass": 17, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 0}}, "4": {"suite_name": "test/api_tests/djnago_app/test_django_user/get_user/test_get_user.py", "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_get_user", "rerun": "0"}}, "status": {"total_pass": 1, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 0}}, "5": {"suite_name": "test/api_tests/djnago_app/test_django_user/get_users/test_get_users.py", "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_get_all_users", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_get_all_users_with_params", "rerun": "0"}}, "status": {"total_pass": 2, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 0}}, "6": {"suite_name": "test/api_tests/djnago_app/test_django_user/get_users/test_unexpected_method_users.py", "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_unexpected_method_all_users_with_params[delete]", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_unexpected_method_all_users_with_params[put]", "rerun": "0"}, "2": {"status": "FAIL", "message": "   AttributeError: 'BaseApi' object has no attribute 'path'. Did you mean: 'patch'?\n", "test_name": "test_unexpected_method_all_users_with_params[path]", "rerun": "0"}}, "status": {"total_pass": 2, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}}, "7": {"suite_name": "test/test_add_user_to_role.py", "tests": {"0": {"status": "ERROR", "message": "file C:\\Users\\artem\\PycharmProjects\\do\\test\\test_add_user_to_role.py, line 6\n  def test_add_user_to_role(create_read_role, create_read_user_function_scope):\nE       fixture 'create_read_role' not found\n>       available fixtures: _session_faker, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, extra, extras, faker, include_metadata_in_junit_xml, metadata, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\Users\\artem\\PycharmProjects\\do\\test\\test_add_user_to_role.py:6\n", "test_name": "test_add_user_to_role", "rerun": "0"}, "1": {"status": "ERROR", "message": "file C:\\Users\\artem\\PycharmProjects\\do\\test\\test_add_user_to_role.py, line 17\n  def test_add_user_to_role_twice(create_read_role, create_read_user_function_scope):\nE       fixture 'create_read_role' not found\n>       available fixtures: _session_faker, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, extra, extras, faker, include_metadata_in_junit_xml, metadata, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\Users\\artem\\PycharmProjects\\do\\test\\test_add_user_to_role.py:17\n", "test_name": "test_add_user_to_role_twice", "rerun": "0"}}, "status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 2}}}}, "date": "April 24, 2024", "start_time": 1713944665.3476048, "total_suite": 8, "status": "FAIL", "status_list": {"pass": "28", "fail": "1", "skip": "0", "error": "2", "xpass": "0", "xfail": "1", "rerun": "0"}, "total_tests": "32"}